# Generated by Django 6.0 on 2025-12-29 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem'),
        ('orders', '0003_alter_order_menu_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
