# Generated by Django 6.0 on 2025-12-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_menuitem_is_available_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
