# Generated by Django 6.0 on 2025-12-27 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_remove_menuitem_category_and_more'),
        ('orders', '0002_remove_order_phone_remove_order_restaurant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
